### ISSUE TITLE
Foreign Key Error

### ISSUE THREAD

**Issue by lowvisiondave** [basilfx/SubDaap#4]
When I try to start SubDaap I am getting the follow error message:

sqlite3.OperationalError: unknown column "container_id" in foreign key definition

**Comment by basilfx** [comment]
I have noticed it. Think I'm not that good at managing different releases :-)

I'm currently working hard on a brand new release with many more improvements. I hope to release this newer version soon.

**Comment by basilfx** [comment]
@davidkeefe24 I semi-working v2.0.0 version is in the development branch. I still have to polish a few things, but I think I have implemented the core.

You will need a new version of `flask-daapserver`, which can be installed via `pip install git+https://travis-ci.org/basilfx/flask-daapserver`

**Comment by basilfx** [comment]
Version v2.0.0 is out, which should solve all of these problems :-)
