### ISSUE TITLE
Use folders instead of ID3 tags

### ISSUE THREAD

**Issue by lowvisiondave** [basilfx/SubDaap#8]
Loving the updates! Just wondering if it is possible to add an option use use the Subsonic API for getIndexes rather than getArtists? Currently my library in iTunes gets populated with artists that appear only on Various Artist compilations and I'd like them to appear under Various Artists.

Basically just using the directory structure rather than ID3 tags. Is that a possibility? Thanks

**Comment by basilfx** [comment]
Hi,

I probably won't fix this anytime soon, because I don't have the time currently. You are free to submit a PR though.

Sorry,
Bas
